quarkus.http.host=0.0.0.0
quarkus.http.port=8080

# Change H2 to PostgreSQL
quarkus.datasource.db-kind=postgresql

# Use an Environment Variable for the URL (Best Practice)
# If this is not set, it will default to the H2 one below
quarkus.datasource.jdbc.url=${DATABASE_URL:jdbc:h2:mem:music_db}

quarkus.hibernate-orm.database.generation=update
quarkus.http.limits.max-body-size=50M